#!/bin/bash

# 备份的目标目录
backupdir=/home/akuma/Github/Ubuntu/.zshrc

# 如果目标目录不存在则创建目录
if [ ! -d "$backupdir" ]; then
  mkdir -p "$backupdir"
fi

# 拷贝 .zshrc 到目标目录
cp ~/.zshrc "$backupdir"/zshrc-$(date +%Y-%m-%d-%H:%M).bak
